### ISSUE TITLE
Test Windows Phone

### ISSUE THREAD

**Issue by calonso** [calonso/rails_push_notifications_test#1]
Pinging @lazaronixon to see if he can test the live deployment of this project here https://rails-push-notifications-test.herokuapp.com/ . Specially the Windows Phone push notifications.

**Comment by lazaronixon** [comment]
Ok.. I will test soon as posible.. not is required Pem encoded certificate for test.

**Comment by calonso** [comment]
Really? So under development you can push notifications just by knowing the 'push url' of the destination device?

**Comment by calonso** [comment]
Closing issue as stale.
