### ISSUE TITLE
Regarding Apple Push notification

### ISSUE THREAD

**Issue by chauhanmohit** [calonso/rails_push_notifications_test#2]
How do i set the "passphrase" for both certificate like development and for production certifcate ?Because it give me following error i.e

OpenSSL::PKey::RSAError (Neither PUB key nor PRIV key: not enough data):
  app/controllers/apple_controller.rb:19:in `create'

**Comment by calonso** [comment]
Hi @chauhanmohit 

The current version of the `rails_push_notifications_test` rails project doesn't support it, but don't panic! You still have two options:
1. Export your certificates into pem files without passphrase `openssl pkcs12 -in <your .p12 file> -out <your .pem destination> -nodes -clcerts`
2. Improve the [rails_push_notifications](https://github.com/calonso/rails-push-notifications) project to use the version `0.4.0` of [ruby-push-notifications](https://github.com/calonso/ruby-push-notifications), that actually supports it. See: [https://github.com/calonso/ruby-push-notifications/blob/master/lib/ruby-push-notifications/apns/apns_connection.rb#L30](https://github.com/calonso/ruby-push-notifications/blob/master/lib/ruby-push-notifications/apns/apns_connection.rb#L30)

Let me know if you need any more help.

**Comment by ramthakur1991** [comment]
Thanks @calonso  
Yeah both of the options are valuable , right now I'm going to use the 1st option if it requires then definitely move to 2nd options

Thanks again

**Comment by calonso** [comment]
Will @ramthakur1991 or @chauhanmohit be up for improving the [rails_push_notifications](https://github.com/calonso/rails-push-notifications) project to use the `0.4.0` version of [ruby-push-notifications](https://github.com/calonso/ruby-push-notifications) so that pem passphrases are supported?
I'll give you as much support as you require for it.

In the meantime I'm closing this issue.

**Comment by ramthakur1991** [comment]
Thanks @calonso

Yeah Please close that issue . I'll fork the new version i.e 0.4.0
